# https://taskfile.dev

version: "3"

output: prefixed

vars:
  LIB_DIR: ./src/lib

tasks:
  dev:
    deps:
      - task: dev:server
        vars:
          API_BASE_URL: "https://snippetbox.localhost/api"
      - task: gen:spec
        vars:
          API_BASE_URL: "https://snippetbox.localhost/api"

  dev:server:
    desc: "Runs dev server for SvelteKit frontend"
    cmd: PUBLIC_API_BASE_URL={{.API_BASE_URL}} pnpm dev

  gen:spec:
    desc: "Generates types from openapi spec"
    cmd: |
      echo "Waiting for backend server (via Caddy) to be ready..."
      until curl -sk https://snippetbox.localhost/api/health 1>/dev/null 2>&1; do
        echo "Backend server not ready yet, waiting..."
        sleep 1
      done
      API_BASE_URL={{.API_BASE_URL | default "http://localhost:4000"}} pnpm gen:spec
    generates:
      - "{{.LIB_DIR}}/api/schema.d.ts"
