# https://taskfile.dev

version: "3"

includes:
  api:
    taskfile: ./apps/api/Taskfile.yaml
    dir: ./apps/api
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web

output: prefixed

vars:
  # same name as container name of service `db` in `compose.yaml`
  DB_CONTAINER_NAME: postgres

tasks:
  default:
    cmd: "task --list-all"

  dev:services:
    internal: true
    deps: [api:dev, api:db:logs, web:dev]

  dev:
    desc: "Starts all services for local development"
    cmds:
      - task: api:db:start
      - |
        echo "Waiting for database to be ready..."
        # inspired by https://stackoverflow.com/questions/46516584/docker-check-if-postgres-is-ready
        until docker exec {{.DB_CONTAINER_NAME}} pg_isready -t 90; do echo "Database not ready yet, waiting..."; sleep 2; done
      - task: dev:services
