# https://taskfile.dev

version: "3"

includes:
  api:
    taskfile: ./apps/api/Taskfile.yaml
    dir: ./apps/api
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web

output: prefixed

vars:
  # same name as container name of service `db` in `apps/api/compose.yaml`
  DB_CONTAINER_NAME: postgres
  # same name as container name of service `cache` in `apps/api/compose.yaml`
  CACHE_CONTAINER_NAME: redis

tasks:
  default:
    cmd: "task --list-all"

  dev:services:
    internal: true
    deps: [caddy, api:dev, api:logs, web:dev]

  dev:
    desc: "Starts all services for local development"
    cmds:
      - task: api:docker
      - |
        echo "Waiting for database to be ready..."
        # inspired by https://stackoverflow.com/questions/46516584/docker-check-if-postgres-is-ready
        until docker exec {{.DB_CONTAINER_NAME}} pg_isready -t 90; do echo "Database not ready yet, waiting..."; sleep 2; done
      - task: dev:services

  copy-tls-file:
    internal: true
    cmds:
      - cp "./openssl/{{.PEM_FILE}}" apps/{{.SERVICE}}/tls/
    status:
      - ! test -f apps/{{.SERVICE}}/tls/{{.PEM_FILE}}

  copy-tls-files:
    internal: true
    deps:
      - task: copy-tls-file
        vars: { PEM_FILE: "certs-chain.pem", SERVICE: "api" }
      - task: copy-tls-file
        vars: { PEM_FILE: "key.pem", SERVICE: "api" }
      - task: copy-tls-file
        vars: { PEM_FILE: "certs-chain.pem", SERVICE: "web" }
      - task: copy-tls-file
        vars: { PEM_FILE: "key.pem", SERVICE: "web" }

  caddy:
    desc: "Starts caddy for reverse proxy"
    deps: [copy-tls-files]
    cmd: caddy run
